name: push-tofu-apply

on:
  push:
    branches:
      - main

jobs:
  apply:
    name: Apply Change
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'infrastructure'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Tofu
        uses: opentofu/setup-opentofu@v1

      - name: Init
        run: tofu init
        env:
            TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

      - name: Validate
        run: tofu validate
        
      - name: Apply
        env:
            TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
            TF_VAR_pvt_key: ${{ secrets.PVT_KEY }}
            TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
        run: tofu apply -input=false -auto-approve