name: push-tofu-apply

on:
  push:
    branches:
      - main

jobs:
  apply:
    name: Apply Change
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'infrastructure'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Tofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_wrapper: false
      - name: Init
        run: tofu init
      - name: Validate
        run: tofu validate
      - name: Apply
        env:
            TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
            TF_VAR_pvt_key: ${{ secrets.PVT_KEY }}
        run: tofu apply -input=false -auto-approve